// Transforms text into caveman speak
const CavemanMode = (() => {
  const REPLACEMENTS = [
    [/\bI am\b/gi, 'ME BE'],
    [/\bI'm\b/gi, 'ME BE'],
    [/\bI'll\b/gi, 'ME GONNA'],
    [/\bI've\b/gi, 'ME HAVE'],
    [/\bI'd\b/gi, 'ME WANT'],
    [/\bI\b/g, 'ME'],
    [/\bwe are\b/gi, 'WE BE'],
    [/\bwe're\b/gi, 'WE BE'],
    [/\bwe\b/gi, 'WE'],
    [/\byou are\b/gi, 'YOU BE'],
    [/\byou're\b/gi, 'YOU BE'],
    [/\byou\b/gi, 'YOU'],
    [/\bhe is\b/gi, 'HE BE'],
    [/\bshe is\b/gi, 'SHE BE'],
    [/\bit is\b/gi, 'IT BE'],
    [/\bthey are\b/gi, 'THEY BE'],
    [/\bthey're\b/gi, 'THEY BE'],
    [/\bthey\b/gi, 'THEY'],
    [/\bis\b/gi, 'BE'],
    [/\bare\b/gi, 'BE'],
    [/\bam\b/gi, 'BE'],
    [/\bwas\b/gi, 'WAS'],
    [/\bwere\b/gi, 'WAS'],
    [/\bwill\b/gi, 'GONNA'],
    [/\bwould\b/gi, 'WANT'],
    [/\bcould\b/gi, 'CAN'],
    [/\bshould\b/gi, 'MUST'],
    [/\bhave\b/gi, 'HAVE'],
    [/\bhas\b/gi, 'HAVE'],
    [/\bhad\b/gi, 'HAD'],
    [/\bdo not\b/gi, 'NO'],
    [/\bdon't\b/gi, 'NO'],
    [/\bdoes not\b/gi, 'NO'],
    [/\bdoesn't\b/gi, 'NO'],
    [/\bcannot\b/gi, 'NO CAN'],
    [/\bcan't\b/gi, 'NO CAN'],
    [/\bvery\b/gi, 'BIG BIG'],
    [/\breally\b/gi, 'BIG'],
    [/\bextremely\b/gi, 'MEGA BIG'],
    [/\bgreat\b/gi, 'GREAT'],
    [/\bgood\b/gi, 'GOOD'],
    [/\bbad\b/gi, 'BAD'],
    [/\bthe\b/gi, ''],
    [/\ba\b/gi, ''],
    [/\ban\b/gi, ''],
    [/\bmy\b/gi, 'ME'],
    [/\byour\b/gi, 'YOU'],
    [/\bhis\b/gi, 'HIM'],
    [/\bher\b/gi, 'HER'],
    [/\bits\b/gi, 'IT'],
    [/\bour\b/gi, 'WE'],
    [/\btheir\b/gi, 'THEY'],
    [/\bfood\b/gi, 'FOOD'],
    [/\bfire\b/gi, 'FIRE'],
    [/\bwater\b/gi, 'WATER'],
    [/\brun\b/gi, 'RUN'],
    [/\bhide\b/gi, 'HIDE'],
    [/\bkill\b/gi, 'SMASH'],
    [/\bfight\b/gi, 'FIGHT'],
    [/\beat\b/gi, 'EAT'],
    [/\bsleep\b/gi, 'SLEEP'],
    [/\bgo\b/gi, 'GO'],
    [/\bcome\b/gi, 'COME'],
    [/\bwant\b/gi, 'WANT'],
    [/\bneed\b/gi, 'NEED'],
    [/\blike\b/gi, 'LIKE'],
    [/\blove\b/gi, 'LOVE BIG'],
    [/\bhate\b/gi, 'HATE'],
    [/\bknow\b/gi, 'KNOW'],
    [/\bthink\b/gi, 'THINK'],
    [/\bsee\b/gi, 'SEE'],
    [/\bhear\b/gi, 'HEAR'],
    [/\bhelp\b/gi, 'HELP'],
    [/\bwork\b/gi, 'WORK'],
    [/\bmake\b/gi, 'MAKE'],
    [/\bbring\b/gi, 'BRING'],
    [/\bgive\b/gi, 'GIVE'],
    [/\btake\b/gi, 'TAKE'],
    [/\bput\b/gi, 'PUT'],
    [/\bwhere\b/gi, 'WHERE'],
    [/\bwhen\b/gi, 'WHEN'],
    [/\bwhat\b/gi, 'WHAT'],
    [/\bwho\b/gi, 'WHO'],
    [/\bhow\b/gi, 'HOW'],
    [/\bwhy\b/gi, 'WHY'],
    [/\byes\b/gi, 'UGH YES'],
    [/\bno\b/gi, 'NO'],
    [/\bokay\b/gi, 'OK'],
    [/\bok\b/gi, 'OK'],
    [/\bplease\b/gi, 'PLEASE'],
    [/\bthanks\b/gi, 'GRUNT THANKS'],
    [/\bthank you\b/gi, 'GRUNT THANKS'],
    [/\bhello\b/gi, 'UGH'],
    [/\bhi\b/gi, 'UGH'],
    [/\bhey\b/gi, 'UGH'],
    [/\bgoodbye\b/gi, 'GO NOW'],
    [/\bbye\b/gi, 'GO NOW'],
    [/\bsorry\b/gi, 'ME WRONG'],
    [/\btomorrow\b/gi, 'NEXT SUN'],
    [/\byesterday\b/gi, 'LAST SUN'],
    [/\btoday\b/gi, 'THIS SUN'],
    [/\bhouse\b/gi, 'CAVE'],
    [/\bhome\b/gi, 'CAVE'],
    [/\bcar\b/gi, 'FAST ROCK'],
    [/\bphone\b/gi, 'TALK ROCK'],
    [/\bcomputer\b/gi, 'MAGIC BOX'],
    [/\binternet\b/gi, 'BIG WEB'],
    [/\bmoney\b/gi, 'SHINY ROCK'],
    [/\bfriend\b/gi, 'TRIBE'],
    [/\bfriends\b/gi, 'TRIBE'],
    [/\benemy\b/gi, 'FOE'],
    [/\benemies\b/gi, 'FOES'],
    [/\bdog\b/gi, 'TAME WOLF'],
    [/\bcat\b/gi, 'SMALL BEAST'],
  ];

  function clean(text) {
    let out = text;
    for (const [pattern, replacement] of REPLACEMENTS) {
      out = out.replace(pattern, replacement);
    }
    // collapse multiple spaces
    out = out.replace(/ {2,}/g, ' ').trim();
    // uppercase everything
    out = out.toUpperCase();
    // add UGH prefix to each sentence
    out = out.replace(/([.!?]+)/g, '$1\nUGH. ');
    // clean trailing UGH
    out = out.replace(/UGH\.\s*$/g, '').trim();
    return out;
  }

  return { transform: clean };
})();
